[package]
name = "emailspamdetection"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3"
linfa = "0.6"
linfa-logistic = "0.6"
ndarray = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
